apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ingress-nginx.yaml

patches:
- patch: |
    - op: add
      path: /metadata/labels
      value:
        pod-security.kubernetes.io/enforce: restricted
  target:
    kind: Namespace
