apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: ingress-nginx
  includeCRDs: true
  valuesFile: helm-values.yaml
  releaseName: ingress-nginx
  namespace: ingress-nginx
  version: 4.11.0
  repo: https://kubernetes.github.io/ingress-nginx

patches:
- target:
    kind: Namespace
  patch: |
    - op: add
      path: /metadata/labels
      value:
        pod-security.kubernetes.io/enforce: restricted
